# Server Port Configuration
server:
  port: 9091

error:
  include-stacktrace: never   # API response mein lamba error nahi dikhega
  include-message: always

# Profile Configuration
spring:
  profiles:
    active: local
  application:
    name: Auth_service

  # Oracle & Datasource Configuration
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: AuthHikariCP
      connection-timeout: 10000 # Startup delay kam karne ke liye
      initialization-fail-timeout: 0

  # JPA & Hibernate Optimization
  jpa:
    show-sql: ${jpa.show-sql}
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${jpa.properties.hibernate.format_sql}
        boot.allow_jdbc_metadata_access: false
        default_schema: SYSTEM 
        jdbc.fetch_size: 100
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  # JPA Bootstrap mode 
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  config:
    import:
      - optional:configserver:http://localhost:9092

# Logging Configuration (Colorful + Short Error Logs)
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} : %msg%n%wEx{1}"
  level:
    root: INFO
    org.hibernate.orm.connections.pooling: ERROR # Faltu pooling logs band karne ke liye

# Management / Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

# JWT Configuration
jwt:
   secret : ${JWT_SECRET}
   expiration : 3600000
   issuer : vikas-app
